BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "entries" (
	"id"	INTEGER,
	"check_in"	DATETIME NOT NULL,
	"check_out"	DATETIME,
	"note"	TEXT,
	"created_at"	DATETIME DEFAULT CURRENT_TIMESTAMP,
	"task_id"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "tasks" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"description"	TEXT,
	"created_at"	DATETIME DEFAULT CURRENT_TIMESTAMP,
	"active"	INTEGER NOT NULL DEFAULT 1,
	"deleted"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
